/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Identifiant URL (ex: "home" pour la page d'accueil, "about" pour /about)
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
  };
  layout: (
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        /**
         * Mini-tag à gauche de l'eyebrow (ex: BTP, BÊTA)
         */
        badgePrefix?: string | null;
        /**
         * Texte de l'eyebrow (ex: « Pensé par et pour les artisans »)
         */
        badge?: string | null;
        /**
         * Entoure les mots à mettre en surbrillance avec **double-astérisques**. Saute une ligne avec \n.
         */
        title: string;
        description?: string | null;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        primaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        /**
         * Petit texte sous les boutons (ex: 30 jours • sans CB • sans engagement)
         */
        fineprint?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              showStars?: boolean | null;
              id?: string | null;
            }[]
          | null;
        showMockup?: boolean | null;
        mockBadgeTop?: {
          show?: boolean | null;
          eyebrow?: string | null;
          title?: string | null;
        };
        mockBadgeBottom?: {
          show?: boolean | null;
          title?: string | null;
          subtitle?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        /**
         * Petit texte affiché au-dessus du bandeau de logos
         */
        eyebrow?: string | null;
        clients: {
          name: string;
          weight?: ('400' | '500' | '600' | '700' | '800') | null;
          italic?: boolean | null;
          tracking?: ('tight' | 'normal' | 'wide') | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'logoStrip';
      }
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        preTitle?: string | null;
        /**
         * Utilise **double-astérisques** pour les mots en surbrillance
         */
        title: string;
        description?: string | null;
        features: {
          eyebrow: string;
          /**
           * Première partie du titre (en noir)
           */
          title: string;
          /**
           * Suite du titre, mise en bleu
           */
          accent?: string | null;
          description: string;
          points?:
            | {
                title: string;
                desc?: string | null;
                id?: string | null;
              }[]
            | null;
          mockupVariant?: ('none' | 'devis' | 'signature' | 'dashboard') | null;
          reverse?: boolean | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'features';
      }
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        preTitle?: string | null;
        /**
         * Utilise **double-astérisques** pour les mots en surbrillance
         */
        title: string;
        beforeLabel?: string | null;
        afterLabel?: string | null;
        beforeEyebrow?: string | null;
        afterEyebrow?: string | null;
        rows: {
          before: string;
          after: string;
          id?: string | null;
        }[];
        stats?:
          | {
              value: string;
              label: string;
              sub?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'comparison';
      }
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        preTitle?: string | null;
        /**
         * Utilise **double-astérisques** pour les mots en surbrillance
         */
        title: string;
        description?: string | null;
        plans: {
          name: string;
          /**
           * Prix affiché (ex: 0€, 19€, 25€)
           */
          price: string;
          /**
           * Suffixe à droite (ex: / mois, / 30 jours)
           */
          priceSuffix: string;
          /**
           * Phrase descriptive sous le prix. Utilise **double-astérisques** pour mettre en gras.
           */
          note?: string | null;
          features: {
            text: string;
            id?: string | null;
          }[];
          cta?: {
            label?: string | null;
            href?: string | null;
            variant?: ('primary' | 'outline') | null;
          };
          footnote?: string | null;
          highlight?: boolean | null;
          /**
           * Texte du badge orange
           */
          badge?: string | null;
          id?: string | null;
        }[];
        youngCompany?: {
          show?: boolean | null;
          eyebrow?: string | null;
          title?: string | null;
          /**
           * Utilise **double-astérisques** pour mettre en gras
           */
          description?: string | null;
          cta?: {
            label?: string | null;
            href?: string | null;
          };
        };
        trustItems?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pricing';
      }
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        preTitle?: string | null;
        /**
         * Utilise **double-astérisques** pour les mots en surbrillance
         */
        title: string;
        googleRating?: {
          show?: boolean | null;
          label?: string | null;
          sub?: string | null;
        };
        reviews: {
          name: string;
          role: string;
          /**
           * Métier (ex: Rénovation, Plomberie)
           */
          trade?: string | null;
          content: string;
          stars: number;
          avatarColor?: ('blue' | 'darken' | 'lighten') | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        preTitle?: string | null;
        /**
         * Utilise **double-astérisques** pour les mots en surbrillance
         */
        title: string;
        items: {
          question: string;
          /**
           * Utilise **double-astérisques** pour les mots à mettre en gras
           */
          answer: string;
          id?: string | null;
        }[];
        contactLine?: {
          show?: boolean | null;
          text?: string | null;
          linkLabel?: string | null;
          linkHref?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Ancre HTML pour cibler la section depuis un lien de menu (sans le #). Ex: tarifs, fonctionnalites, faq.
         */
        anchor?: string | null;
        /**
         * Saute une ligne avec \n pour forcer un retour à la ligne dans le titre
         */
        title: string;
        description?: string | null;
        primaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        secondaryCta?: {
          label?: string | null;
          href?: string | null;
        };
        fineprint?: string | null;
        trustItems?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'finalCta';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              anchor?: T;
              badgePrefix?: T;
              badge?: T;
              title?: T;
              description?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              fineprint?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    showStars?: T;
                    id?: T;
                  };
              showMockup?: T;
              mockBadgeTop?:
                | T
                | {
                    show?: T;
                    eyebrow?: T;
                    title?: T;
                  };
              mockBadgeBottom?:
                | T
                | {
                    show?: T;
                    title?: T;
                    subtitle?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoStrip?:
          | T
          | {
              anchor?: T;
              eyebrow?: T;
              clients?:
                | T
                | {
                    name?: T;
                    weight?: T;
                    italic?: T;
                    tracking?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              anchor?: T;
              preTitle?: T;
              title?: T;
              description?: T;
              features?:
                | T
                | {
                    eyebrow?: T;
                    title?: T;
                    accent?: T;
                    description?: T;
                    points?:
                      | T
                      | {
                          title?: T;
                          desc?: T;
                          id?: T;
                        };
                    mockupVariant?: T;
                    reverse?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparison?:
          | T
          | {
              anchor?: T;
              preTitle?: T;
              title?: T;
              beforeLabel?: T;
              afterLabel?: T;
              beforeEyebrow?: T;
              afterEyebrow?: T;
              rows?:
                | T
                | {
                    before?: T;
                    after?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    sub?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              anchor?: T;
              preTitle?: T;
              title?: T;
              description?: T;
              plans?:
                | T
                | {
                    name?: T;
                    price?: T;
                    priceSuffix?: T;
                    note?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                          variant?: T;
                        };
                    footnote?: T;
                    highlight?: T;
                    badge?: T;
                    id?: T;
                  };
              youngCompany?:
                | T
                | {
                    show?: T;
                    eyebrow?: T;
                    title?: T;
                    description?: T;
                    cta?:
                      | T
                      | {
                          label?: T;
                          href?: T;
                        };
                  };
              trustItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              anchor?: T;
              preTitle?: T;
              title?: T;
              googleRating?:
                | T
                | {
                    show?: T;
                    label?: T;
                    sub?: T;
                  };
              reviews?:
                | T
                | {
                    name?: T;
                    role?: T;
                    trade?: T;
                    content?: T;
                    stars?: T;
                    avatarColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              anchor?: T;
              preTitle?: T;
              title?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              contactLine?:
                | T
                | {
                    show?: T;
                    text?: T;
                    linkLabel?: T;
                    linkHref?: T;
                  };
              id?: T;
              blockName?: T;
            };
        finalCta?:
          | T
          | {
              anchor?: T;
              title?: T;
              description?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              fineprint?: T;
              trustItems?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  announcement?: {
    enabled?: boolean | null;
    /**
     * Petite étiquette à gauche (ex: NOUVEAU, BÊTA)
     */
    badge?: string | null;
    /**
     * Message du bandeau. Utilise **double-astérisques** pour mettre des mots en gras.
     */
    message?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  /**
   * Logo affiché dans la barre de navigation
   */
  logo?: (number | null) | Media;
  logoAlt?: string | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  secondaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Logo affiché dans le footer (variante claire / blanche)
   */
  logo?: (number | null) | Media;
  logoAlt?: string | null;
  tagline?: string | null;
  rating?: {
    show?: boolean | null;
    score?: string | null;
    platform?: string | null;
  };
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Utilise {year} pour insérer l'année courante
   */
  copyright?: string | null;
  /**
   * Le ♥ sera remplacé par une icône cœur rouge.
   */
  madeWith?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        badge?: T;
        message?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  logo?: T;
  logoAlt?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  logoAlt?: T;
  tagline?: T;
  rating?:
    | T
    | {
        show?: T;
        score?: T;
        platform?: T;
      };
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  madeWith?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}